from __future__ import annotations

from datagokr.catalog import (
    SERVICE_KEY_ENV_NAMES,
    SERVICE_KEY_PARAM,
    ApiCatalogEntry,
    ParamSpec,
    get_api_catalog,
    get_api_catalog_entry,
)
from datagokr.client import DataGoKrClient
from datagokr.config import DataGoKrConfig
from datagokr.debug import (
    DebugRun,
    debug_error,
    jsonable,
    redact_sensitive,
    save_fixture,
)
from datagokr.models import (
    AgriWeatherObservationStation,
    KwaterSluiceRecord,
    OpenApiPage,
    PublicCulturalFestival,
    PublicFileDataRecord,
    PublicMuseumArtGallery,
    PublicParkingLot,
    PublicSpecialStreet,
    PublicTouristAttraction,
    StandardPage,
)
from datagokr.services import (
    AGRI_WEATHER_STATION_ENDPOINT,
    CULTURAL_FESTIVAL_ENDPOINT,
    FILE_DATASETS,
    KWATER_SLUICE_DAY_ENDPOINT,
    KWATER_SLUICE_HOUR_ENDPOINT,
    KWATER_SLUICE_TEN_MINUTE_ENDPOINT,
    MUSEUM_ART_GALLERY_ENDPOINT,
    PARKING_LOT_ENDPOINT,
    SPECIAL_STREET_ENDPOINT,
    TOURIST_ATTRACTION_ENDPOINT,
    AgriWeatherService,
    CulturalFestivalService,
    FileDataCatalogEntry,
    FileDataService,
    KwaterSluiceService,
    MuseumArtGalleryService,
    ParkingLotService,
    SpecialStreetService,
    TouristAttractionService,
    get_file_dataset,
)
from datagokr.storage import save_to_local, save_to_rustfs

__version__ = "0.1.0"
PROVIDER_NAME = "python-datagokr-api"

__all__ = [
    "AGRI_WEATHER_STATION_ENDPOINT",
    "CULTURAL_FESTIVAL_ENDPOINT",
    "FILE_DATASETS",
    "KWATER_SLUICE_DAY_ENDPOINT",
    "KWATER_SLUICE_HOUR_ENDPOINT",
    "KWATER_SLUICE_TEN_MINUTE_ENDPOINT",
    "MUSEUM_ART_GALLERY_ENDPOINT",
    "PARKING_LOT_ENDPOINT",
    "PROVIDER_NAME",
    "SERVICE_KEY_ENV_NAMES",
    "SERVICE_KEY_PARAM",
    "SPECIAL_STREET_ENDPOINT",
    "TOURIST_ATTRACTION_ENDPOINT",
    "AgriWeatherObservationStation",
    "AgriWeatherService",
    "ApiCatalogEntry",
    "CulturalFestivalService",
    "DataGoKrClient",
    "DataGoKrConfig",
    "DebugRun",
    "FileDataCatalogEntry",
    "FileDataService",
    "KwaterSluiceRecord",
    "KwaterSluiceService",
    "MuseumArtGalleryService",
    "OpenApiPage",
    "ParamSpec",
    "ParkingLotService",
    "PublicCulturalFestival",
    "PublicFileDataRecord",
    "PublicMuseumArtGallery",
    "PublicParkingLot",
    "PublicSpecialStreet",
    "PublicTouristAttraction",
    "SpecialStreetService",
    "StandardPage",
    "TouristAttractionService",
    "__version__",
    "debug_error",
    "get_api_catalog",
    "get_api_catalog_entry",
    "get_file_dataset",
    "jsonable",
    "redact_sensitive",
    "save_fixture",
    "save_to_local",
    "save_to_rustfs",
]

